name: Build and Test

on:
  push:
    branches:
      - main # Change this to the main branch of your repository

jobs:
  build-and-test:
    runs-on: macos-latest # You can change the runner platform if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specifies to use Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install Appium-Python-Client
        pip install selenium

    - name: Execute test.py
      env: # Define environment variables using secrets
        LT_USERNAME: ${{ secrets.LT_USERNAME }} # Use the secret for the LambdaTest username
        LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }} # Use the secret for the LambdaTest access key
      run: python test.py
